### ISSUE TITLE
Problema al instalarlo

### ISSUE THREAD

**Issue by josemmc95** [4nth0nySLT/Huawei-Decoder#1]
Buenas!

No consigo arrancar el setup.py, me da errores y no se como solventarlos.

Llevo varios días intentando desencriptar la clave de mi router y no lo consigo de ninguna forma. Este es el único repositorio que he visto que parece ser que sirva para desencriptarla.

Me gustaría hablar contigo si quisieras.

Un saludo!

**Comment by josemmc95** [comment]
Solucionado.

Aún así, quiero contactar contigo para contribuir por tu grandísima ayuda.

Estoy a la espera de tu respuesta.

**Comment by 4nth0nySLT** [comment]
Hola, disculpa no eh estado activo, que problemas tenias?

**Comment by josemmc95** [comment]
> Hola, disculpa no eh estado activo, que problemas tenias?

Me hacía falta un componente de visual studio para que compilase, pero ya lo instalé y funcionó perfecto.

Por fin he podido sacar la contraseña del PPPoE de mi operador, aunque finalmente no me conecta desde otro router (no me va ni clonando la MAC, VLAN, …).

Muchísimas gracias!!
